hikari: &hikari
  driverClassName: com.mysql.cj.jdbc.Driver
  type: com.zaxxer.hikari.HikariDataSource
spring:
  datasource:
    ds1:
      jdbc-url: jdbc:mysql://localhost:3306/?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
      username: root
      password: 123456
      <<: *hikari